language: node_js
dist: trusty
os: linux

services:
  - docker

node_js:
  - "8"
  - "10"
  - "11"

stages:
  - install
  - build
  - lint
  - test

before_script:
  - set -o pipefail
  - npm install codecov -g
  - docker-compose up -d underbase-db

jobs:
  include:
    - stage: install
      script: npm install

    - stage: build
      script: npm run build
      
    - stage: lint
      script: npm run lint
      
    - stage: test
      script:
        - npm run test
        - codecov -f coverage/*.json
