name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: install
      run: |
        set -o pipefail
        npm install
        npm run bootstrap

    - name: lint
      run: npm run lint

    - name: build
      run: npm run build:clean

    - name: test
      run: |
        docker-compose up -d underbase-db
        npm test

    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage/coverage-final.json
        flags: unittests
        name: codecov-umbrella 
