name: npm CI

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install
      run: |
        set -o pipefail
        npm install
        npm run bootstrap
    - name: build
      run: npm run build:clean
    - name: publish
      run: |
        npm publish
